component output="false" extends="conference.services.BaseEntity" 
{
	property type="string" name="IdentityID";
	property type="conference.repository.autogenerated.Login" name="login";
	property type="numeric" name="conference.repository.autogenerated.person";
	property type="conference.repository.autogenerated.Role[]" name="arrayOfRole"; 
}