component extends="conference.repository.autogenerated.Address"   output="false"
{
	property type="numeric" name="addressTypeID";
	property type="string" name="addressTypeName";
	property type="conference.services.BaseEntity" name="baseEntity"; 
}