component output="false" extends="BaseEntity"
{
	property name="person" type="conference.Repository.AutoGenerated.Person";
	property name="personAddresses" type="conference.Repository.AutoGenerated.Address[]";
	property name="conference" type="conference.Repository.AutoGenerated.Conference";
	property name="lectures" type="conference.Repository.AutoGenerated.Lectures[]";
}