component output="false" extends="BaseEntity"
{
	property name="person" type="CFSummit2016.work.architect03.Repository.AutoGenerated.Person";
	property name="personAddresses" type="CFSummit2016.work.architect03.Repository.AutoGenerated.Address[]";
	property name="conference" type="CFSummit2016.work.architect03.Repository.AutoGenerated.Conference";
	property name="sessions" type="CFSummit2016.work.architect03.Repository.AutoGenerated.Session[]";
}