component ectends="BaseEntity" output="false"
{
	property name="person" type="conference.repository.autogenerated.Person";
	property name="lectures" type="conference.repository.autogenerated.Lecture[]"; 
}