component extends="conference.services.BaseEntity" output="false"
{
	property type="person" name="conference.repository.autogenerated.Person";
	property type="address[]" name="conference.repository.autogenerated.address[]"; 
}